### ISSUE TITLE
todo functionality

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/whiteboard-live#2]
## Value statement - a requirement, not a solution
As a user
I want to add Todos to the whiteboard
so that i can write stuff i have to do

## Acceptance criteria
- [ ] implement the "add todo" function
- [ ] you want to be able to edit and delete the todo aswell

## Tasks
- [ ] add the todo functionality which can be edited and deleted by the user

## Size
medium
